name: mausam
description: Dynamic personalized weather and decision support mobile app.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  http: ^1.2.2
  geolocator: ^13.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env.example
